### ISSUE TITLE
very high CPU usage in LSP mode

### ISSUE THREAD

**Issue by ssandler** [hhvm/hhast#156]
## Symptom

Use VSCode with these configuration options:
```
"hack.useHhast": true,
"hack.hhastLintMode": "open-files",
"hack.hhastPath": "vendor/hhvm/hhast/bin/hhast-lint",
```

Open a workspace with a .hhconfig. It's not necessary to even open any hack files in the editor to repro this.

## Expected Behavior

HHAST should not have much to do unless I'm actively editing code.

## Actual Behavior

The LSP process, which looks like this:
```
hhvm vendor/hhvm/hhast/bin/hhast-lint --mode lsp --from vscode-hack
```

uses >100% CPU forever, draining the computer's battery very quickly.

## Investigation

Used `dtrace` combined with tooling from https://github.com/jvm-profiling-tools to generate a sample and flamegraph (attached).

```
$ ps aux | grep hhast // find PID
$ ./dtrace-java-record-stack $PID
$ ./dtrace-perf-map.pl /tmp/perf-$PID.map < /tmp/dtrace-$PID.data > stack_with_pid_map
$ ./dtrace-java-flames $PID
```

Results:
stack_with_pid_map: https://gist.github.com/ssandler/43e793206ebf5850cc2197d562b287f4
flamegraph: https://gist.github.com/ssandler/9c1fd158059301134a3d4f5e3f30e1e5

**Comment by fredemmott** [comment]
I believe this was fixed a few weeks back with some changes to hsl-experimental - can you confirm?

**Comment by ssandler** [comment]
That change helped. I think you had a theory about orphaned hhast processes staying around and not exiting, and that is still an occasional issue for some folks. I haven't been able to reliably reproduce that myself, but several people have reported still seeing this issue and `ps aux | grep hhast` generally shows one newer and one older process from vscode where there would normally be only one. I'm not sure if HHAST can detect when the socket is in this state and just exit the orphaned child process?

**Comment by fredemmott** [comment]
I've seen that a few times when I start vscode on an old rev with an old HHAST+hh-clilib, or forgotten to run composer install - is it likely that something similar is happening here?

**Comment by fredemmott** [comment]
Also do you have 3.30.3 or 3.30.4? 3.30.3 fixed the busy spinning, 3.30.4 fixed blocking-forever-on-socket problems.

**Comment by ssandler** [comment]
> I've seen that a few times when I start vscode on an old rev with an old HHAST+hh-clilib, or forgotten to run composer install - is it likely that something similar is happening here?

I don't think it's this, as it's been weeks since we updated the dependencies and I don't think folks are bouncing between versions.

> Also do you have hsl-experimental 3.30.3 or 3.30.4? 3.30.3 fixed the busy spinning, 3.30.4 fixed blocking-forever-on-socket problems.

Currently 3.30.3, will update to 3.30.4. Thanks!

**Comment by fredemmott** [comment]
Another visualization of those samples (hopefully clearer for recursive calls than FlameGraphs are):

![perf](https://user-images.githubusercontent.com/360927/56912347-eeaafa80-6a63-11e9-90c6-22cceb4d6349.png)

**Comment by fredemmott** [comment]
I think we need an updated stack; that is pretty much dominated by the already-fixed HSL IO issue

**Comment by fredemmott** [comment]
Closing in favor of https://github.com/hhvm/user-documentation/issues/637  ; I don't think there's anythign actionable left here

**Comment by fredemmott** [comment]
whoops, opened that on the wrong repo

**Comment by fredemmott** [comment]
#163
